**Dataset:** StudentsPerformance.csv

**Context:** Online Education

This project applies **SQL techniques such as grouping, binning, and aggregation** to analyze academic performance data from an online education platform.
I transformed continuous variables into categorized ranges to better understand student profiles, identify patterns in performance, and summarize key statistics.

**Skills demonstrated:** Aggregation, binning, grouping, data categorization, metric generation
**Language:** SQL

In [1]:
Question_1 = _dntk.execute_sql(
  '-- No código abaixo foram criadas bins para cada faixa de idade e através do COUNT foi somada a quantidade de alunos \n-- por cada faixa. O GROUP BY foi chamado para agrupar por faixa etária e o ORDER BY foi utilizado no contexto da\n-- visualização do dataframe.\nSELECT \n    CASE\n        WHEN "math score" BETWEEN 0 AND 40 THEN \'0-40\'\n        WHEN "math score" BETWEEN 41 AND 70 THEN \'41-70\'\n        WHEN "math score" BETWEEN 71 AND 100 THEN \'71-100\'\n    END AS faixa,\n    COUNT(*) AS total_alunos\nFROM StudentsPerformance.csv\nGROUP BY faixa\nORDER BY faixa;\n\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_1

    faixa  total_alunos
0    0-40            50
1   41-70           559
2  71-100           391

In [2]:
Question_2 = _dntk.execute_sql(
  '-- No código SQL abaixo foi criada uma nova tabela chamada "StudentsPerformance_com_faixa" com todas as colunas\n-- do CSV + a coluna faixa_matematica. Ao final foi feito um SELECT para mostrar as 10 primeiras linhas da nova \n-- tabela criada.\n\nCREATE OR REPLACE TABLE StudentsPerformance_com_faixa AS\nSELECT\n    *, \n    CASE\n        WHEN "math score" BETWEEN 0 AND 40 THEN \'Baixo (0-40)\'\n        WHEN "math score" BETWEEN 41 AND 70 THEN \'Médio (41-70)\'\n        WHEN "math score" BETWEEN 71 AND 100 THEN \'Alto (71-100)\'\n        ELSE \'Fora da faixa\'\n    END AS faixa_matematica\nFROM StudentsPerformance.csv;\n\nSELECT * \nFROM StudentsPerformance_com_faixa\nLIMIT 10;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_2

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,faixa_matematica
0,female,group B,bachelor's degree,standard,none,72,72,74,Alto (71-100)
1,female,group C,some college,standard,completed,69,90,88,Médio (41-70)
2,female,group B,master's degree,standard,none,90,95,93,Alto (71-100)
3,male,group A,associate's degree,free/reduced,none,47,57,44,Médio (41-70)
4,male,group C,some college,standard,none,76,78,75,Alto (71-100)
5,female,group B,associate's degree,standard,none,71,83,78,Alto (71-100)
6,female,group B,some college,standard,completed,88,95,92,Alto (71-100)
7,male,group B,some college,free/reduced,none,40,43,39,Baixo (0-40)
8,male,group D,high school,free/reduced,completed,64,64,67,Médio (41-70)
9,female,group B,high school,free/reduced,none,38,60,50,Baixo (0-40)

In [3]:
Question_3 = _dntk.execute_sql(
  '-- No código abaixo foram selecionadas três colunas da tabela "StudentsPerformance_com_faixa": "faixa_matematica", \n-- "reading score" e "writing score". Destas duas últimas foi calculada a média através da função AVG e mostrada \n-- em um dataframe SQL.\n\nSELECT \n    faixa_matematica,\n    ROUND(AVG("reading score"), 2) AS \'media_reading\',\n    ROUND(AVG("writing score"), 2) AS \'media_writing\'\nFROM StudentsPerformance_com_faixa\nGROUP BY faixa_matematica\nORDER BY faixa_matematica;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_3

  faixa_matematica  media_reading  media_writing
0    Alto (71-100)          80.69          79.66
1     Baixo (0-40)          43.44          40.12
2    Médio (41-70)          63.41          62.43

In [4]:
Question_4 = _dntk.execute_sql(
  '-- No código abaixo a coluna "reading score" foi categorizada em três bins, ou seja \'Baixo (0-40)\', \'Médio (41-70)\'\n-- e \'Alto (71-100)\' e para uma melhor visualização foi chamada a tabela StudentsPerformance_com_faixa onde a \n-- coluna faixa_matematica existe.\n\nSELECT\n    *, \n    CASE\n        WHEN "reading score" BETWEEN 0 AND 40 THEN \'Baixo (0-40)\'\n        WHEN "reading score" BETWEEN 41 AND 70 THEN \'Médio (41-70)\'\n        WHEN "reading score" BETWEEN 71 AND 100 THEN \'Alto (71-100)\'\n        ELSE \'Fora da faixa\'\n    END AS faixa_letura\nFROM StudentsPerformance_com_faixa;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_4

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,faixa_matematica,faixa_letura
0,female,group B,bachelor's degree,standard,none,72,72,74,Alto (71-100),Alto (71-100)
1,female,group C,some college,standard,completed,69,90,88,Médio (41-70),Alto (71-100)
2,female,group B,master's degree,standard,none,90,95,93,Alto (71-100),Alto (71-100)
3,male,group A,associate's degree,free/reduced,none,47,57,44,Médio (41-70),Médio (41-70)
4,male,group C,some college,standard,none,76,78,75,Alto (71-100),Alto (71-100)
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,Alto (71-100),Alto (71-100)
996,male,group C,high school,free/reduced,none,62,55,55,Médio (41-70),Médio (41-70)
997,female,group C,high school,free/reduced,completed,59,71,65,Médio (41-70),Alto (71-100)
998,female,group D,some college,standard,completed,68,78,77,Médio (41-70),Alto (71-100)
999,female,group D,some college,free/reduced,none,77,86,86,Alto (71-100),Alto (71-100)

In [5]:
Question_5 = _dntk.execute_sql(
  '-- No código abaixo as colunas "gender" e "reading score" foram chamadas da tabela "StudentsPerformance_com_faixa".\n-- A coluna "reading score" foi categorizada em três bins \'Baixo (0-40)\', \'Médio (41-70)\', \'Alto (71-100)\' e organizada\n-- em uma nova coluna "faixa_leitura".\n-- A coluna "total_alunos" foi criada através da função de agregação COUNT com o objetivo de trazer o numero total \n-- de alunos por gênero e por faixa de leitura.\n\nSELECT \n    gender, \n    CASE\n        WHEN "reading score" BETWEEN 0 AND 40 THEN \'Baixo (0-40)\'\n        WHEN "reading score" BETWEEN 41 AND 70 THEN \'Médio (41-70)\'\n        WHEN "reading score" BETWEEN 71 AND 100 THEN \'Alto (71-100)\'\n        ELSE \'fora da faixa\'\n    END AS faixa_leitura,\n    COUNT(*) AS total_alunos\nFROM StudentsPerformance_com_faixa\nGROUP BY gender, faixa_leitura\nORDER BY gender, faixa_leitura;\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_5

   gender  faixa_leitura  total_alunos
0  female  Alto (71-100)           302
1  female   Baixo (0-40)            12
2  female  Médio (41-70)           204
3    male  Alto (71-100)           185
4    male   Baixo (0-40)            15
5    male  Médio (41-70)           282

In [6]:
Question_6 = _dntk.execute_sql(
  '-- No código abaixo foi utilizada a função de agregação COUNT com o parâmetro DISTINCT para fornecer a quantidade de \n-- valores únicos das colunas "parental level of education" e "race/ethnicity".\n\nSELECT\n    COUNT(DISTINCT "parental level of education") AS niveis_educacao_pais,\n    COUNT(DISTINCT "race/ethnicity") AS grupos_unicos_raca\nFROM StudentsPerformance.csv;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_6

   niveis_educacao_pais  grupos_unicos_raca
0                     6                   5

In [7]:
Question_7 = _dntk.execute_sql(
  '-- No código abaixo foi feita uma análise em cima da coluna "writing score" através de uma distribuição por faixas:\n-- \'Baixo 0-40\',\'Médio 41-70\' e \'Alto 71-100\', que foram contabilizadas em uma coluna chamada "total_alunos".\n\nCREATE OR REPLACE TABLE Distribuicao_escrita AS\nSELECT\n    CASE \n        WHEN "writing score" BETWEEN 0 AND 40 THEN \'Baixo 0-40\'\n        WHEN "writing score" BETWEEN 41 AND 70 THEN \'Médio 41-70\'\n        WHEN "writing score" BETWEEN 71 AND 100 THEN \'Alto 71-100\'\n        ELSE \'fora da faixa\'\n    END AS faixa_escrita,\n    COUNT (*) AS total_alunos\nFROM StudentsPerformance_com_faixa\nGROUP BY faixa_escrita\nORDER BY faixa_escrita;\n\nSELECT * \nFROM Distribuicao_escrita;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_7

  faixa_escrita  total_alunos
0   Alto 71-100           456
1    Baixo 0-40            35
2   Médio 41-70           509

In [8]:
Question_8 = _dntk.execute_sql(
  '-- No código abaixo foi criada uma tabela chamada "Analise_Curso_Preparacao" onde foram analisadas a média e a \n-- amplitude (ou seja, a diferença) dos valores das colunas "math score", "writing score" e "reading score" e \n-- organizadas em dois grupos (registros) "none" e "completed".\n-- Após análise da tabela criada pode-se verificar que, os alunos que concluíram o Teste de Preparação possuem notas\n-- melhores do que aqueles que não concluíram. Além disso verifica-se que a amplitude menor para as notas sugere que\n-- os resultados desses alunos são mais concentrados e consistentes.\n\nCREATE OR REPLACE TABLE Analise_Curso_Preparacao AS\nSELECT \n    "test preparation course",\n    ROUND(AVG("math score"), 2) AS media_math,\n    ROUND(AVG("reading score"), 2) AS media_reading,\n    ROUND(AVG("writing score"), 2) AS media_writing, \n    MAX("math score") - MIN("math score") AS amplitude_math,\n    MAX("reading score") - MIN("reading score") AS amplitude_reading,\n    MAX("writing score") - MIN("writing score") AS amplitude_writing\nFROM StudentsPerformance_com_faixa\nGROUP BY "test preparation course";\n\nSELECT * FROM Analise_Curso_Preparacao;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Question_8

,test preparation course,media_math,media_reading,media_writing,amplitude_math,amplitude_reading,amplitude_writing
0,none,64.08,66.53,64.50,100,83,90
1,completed,69.70,73.89,74.42,77,63,64

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=b50e4344-4647-4a93-b699-42e32f41625a' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>